#!/bin/sh
# Write a Verilator waiver file for the vendored cores and print its path.
#
# It is generated rather than committed because Verilator rejects a whole
# waiver file that names a rule that version does not know -- which is how a
# file written against the newest Verilator broke the lint on CI's older one.
# Each rule is probed first and only the ones that exist go in.
#
# Source it with `here` already set to the sim directory (every script that
# uses it computes that first); when a file is sourced, $0 is still the
# caller's, so it cannot work that out for itself.
#
#   . "$here/waivers.sh"   ->  $WAIVERS
set -e
WAIVERS="$here/waivers.vlt"

_rules="ALWCOMBORDER BLKANDNBLK BLKLOOPINIT BLKSEQ CASEINCOMPLETE CASEOVERLAP
        CASEX CMPCONST COMBDLY ENUMVALUE EOFNEWLINE GENUNNAMED IMPLICIT
        INITIALDLY LATCH MULTIDRIVEN PINMISSING PROCASSINIT REALCVT SELRANGE
        SIDEEFFECT STMTDLY SYNCASYNCNET UNDRIVEN UNOPTFLAT UNSIGNED
        UNUSEDGENVAR VARHIDDEN WIDTHCONCAT WIDTHEXPAND WIDTHTRUNC ASCRANGE"
_probe=$(mktemp -d)
echo 'module lintprobe; endmodule' > "$_probe/lintprobe.v"

# the patterns are for Verilator, not the shell
set -f
{
  echo '`verilator_config'
  echo '// Generated by sim/waivers.sh. The vendored cores are kept exactly as'
  echo '// upstream wrote them so they stay diffable; nothing under rtl/ is'
  echo '// waived, and a genuine dont-care there gets its own narrow lint_off'
  echo '// in the source with the reason on the line above it.'
  for _r in $_rules; do
      verilator --lint-only "-Wno-$_r" "$_probe/lintprobe.v" >/dev/null 2>&1 || continue
      for _f in '*/cpu-fx68k/*' '*/cpu-tv80/*' '*/sound-jt03/*' '*/sound-jt49/*'; do
          echo "lint_off -rule $_r -file \"$_f\""
      done
  done
} > "$WAIVERS"
set +f
rm -rf "$_probe"
export WAIVERS
