#!/bin/sh
# Regenerate rtl/index.qip: every RTL file the core needs, in a stable order.
# Run from the repo root whenever a file is added to or removed from rtl/ or
# modules/.  Vendored modules are picked up by directory: every .sv and .v
# under modules/<name>/ is listed, so record what each one is in
# modules/VENDOR.md, and delete what the core does not instantiate.
set -e
cd "$(dirname "$0")/.."
out=rtl/index.qip
{
echo "# =============================================================================="
echo "# Core RTL -- generated by tools/gen_qip.sh, do not edit"
echo "# =============================================================================="
echo 'set_global_assignment -name SEARCH_PATH [file join $::quartus(qip_path) ""]'
for f in $(cd rtl && ls *.sv 2>/dev/null | sort); do
    echo "set_global_assignment -name SYSTEMVERILOG_FILE [file join \$::quartus(qip_path) \"$f\"]"
done
for d in $(ls -d modules/*/ 2>/dev/null | sort); do
    m=$(basename "$d")
    echo ""
    echo "# modules/$m (see modules/VENDOR.md)"
    echo "set_global_assignment -name SEARCH_PATH [file join \$::quartus(qip_path) \"../modules/$m\"]"
    for f in $(cd "$d" && ls *.sv 2>/dev/null | sort); do
        echo "set_global_assignment -name SYSTEMVERILOG_FILE [file join \$::quartus(qip_path) \"../modules/$m/$f\"]"
    done
    for f in $(cd "$d" && ls *.v 2>/dev/null | sort); do
        echo "set_global_assignment -name VERILOG_FILE [file join \$::quartus(qip_path) \"../modules/$m/$f\"]"
    done
done
} > "$out"
echo "wrote $out"
